package mypkg;
// Generated 10-ene-2018 11:47:00 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Libros generated by hbm2java
 */
public class Libros  implements java.io.Serializable {


     private Integer codigo;
     private String titulo;
     private String autor;
     private int anno;
     private int numeroEjemplares;
     private Set<Prestamos> prestamoses = new HashSet<Prestamos>(0);

    public Libros() {
    }

	
    public Libros(String titulo, String autor, int anno, int numeroEjemplares) {
        this.titulo = titulo;
        this.autor = autor;
        this.anno = anno;
        this.numeroEjemplares = numeroEjemplares;
    }
    public Libros(String titulo, String autor, int anno, int numeroEjemplares, Set<Prestamos> prestamoses) {
       this.titulo = titulo;
       this.autor = autor;
       this.anno = anno;
       this.numeroEjemplares = numeroEjemplares;
       this.prestamoses = prestamoses;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public String getAutor() {
        return this.autor;
    }
    
    public void setAutor(String autor) {
        this.autor = autor;
    }
    public int getAnno() {
        return this.anno;
    }
    
    public void setAnno(int anno) {
        this.anno = anno;
    }
    public int getNumeroEjemplares() {
        return this.numeroEjemplares;
    }
    
    public void setNumeroEjemplares(int numeroEjemplares) {
        this.numeroEjemplares = numeroEjemplares;
    }
    public Set<Prestamos> getPrestamoses() {
        return this.prestamoses;
    }
    
    public void setPrestamoses(Set<Prestamos> prestamoses) {
        this.prestamoses = prestamoses;
    }




}


