package mypkg;
// Generated 10-ene-2018 11:47:00 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * PrestamosId generated by hbm2java
 */
public class PrestamosId  implements java.io.Serializable {


     private int codigoLibro;
     private int codigoSocio;
     private Date fechaInicio;

    public PrestamosId() {
    }

    public PrestamosId(int codigoLibro, int codigoSocio, Date fechaInicio) {
       this.codigoLibro = codigoLibro;
       this.codigoSocio = codigoSocio;
       this.fechaInicio = fechaInicio;
    }
   
    public int getCodigoLibro() {
        return this.codigoLibro;
    }
    
    public void setCodigoLibro(int codigoLibro) {
        this.codigoLibro = codigoLibro;
    }
    public int getCodigoSocio() {
        return this.codigoSocio;
    }
    
    public void setCodigoSocio(int codigoSocio) {
        this.codigoSocio = codigoSocio;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PrestamosId) ) return false;
		 PrestamosId castOther = ( PrestamosId ) other; 
         
		 return (this.getCodigoLibro()==castOther.getCodigoLibro())
 && (this.getCodigoSocio()==castOther.getCodigoSocio())
 && ( (this.getFechaInicio()==castOther.getFechaInicio()) || ( this.getFechaInicio()!=null && castOther.getFechaInicio()!=null && this.getFechaInicio().equals(castOther.getFechaInicio()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCodigoLibro();
         result = 37 * result + this.getCodigoSocio();
         result = 37 * result + ( getFechaInicio() == null ? 0 : this.getFechaInicio().hashCode() );
         return result;
   }   


}


