package mypkg;
// Generated 10-ene-2018 11:47:00 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Prestamos generated by hbm2java
 */
public class Prestamos  implements java.io.Serializable {


     private PrestamosId id;
     private Libros libros;
     private Socios socios;
     private Date fechaFin;
     private Date fechaDevolucion;

    public Prestamos() {
    }

	
    public Prestamos(PrestamosId id, Libros libros, Socios socios, Date fechaFin) {
        this.id = id;
        this.libros = libros;
        this.socios = socios;
        this.fechaFin = fechaFin;
    }
    public Prestamos(PrestamosId id, Libros libros, Socios socios, Date fechaFin, Date fechaDevolucion) {
       this.id = id;
       this.libros = libros;
       this.socios = socios;
       this.fechaFin = fechaFin;
       this.fechaDevolucion = fechaDevolucion;
    }
   
    public PrestamosId getId() {
        return this.id;
    }
    
    public void setId(PrestamosId id) {
        this.id = id;
    }
    public Libros getLibros() {
        return this.libros;
    }
    
    public void setLibros(Libros libros) {
        this.libros = libros;
    }
    public Socios getSocios() {
        return this.socios;
    }
    
    public void setSocios(Socios socios) {
        this.socios = socios;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }
    public Date getFechaDevolucion() {
        return this.fechaDevolucion;
    }
    
    public void setFechaDevolucion(Date fechaDevolucion) {
        this.fechaDevolucion = fechaDevolucion;
    }




}


