package mypkg;
// Generated 10-ene-2018 11:47:00 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Socios generated by hbm2java
 */
public class Socios  implements java.io.Serializable {


     private Integer codigo;
     private String nombre;
     private String domicilio;
     private int telefono;
     private String correo;
     private Set<Prestamos> prestamoses = new HashSet<Prestamos>(0);

    public Socios() {
    }

	
    public Socios(String nombre, String domicilio, int telefono, String correo) {
        this.nombre = nombre;
        this.domicilio = domicilio;
        this.telefono = telefono;
        this.correo = correo;
    }
    public Socios(String nombre, String domicilio, int telefono, String correo, Set<Prestamos> prestamoses) {
       this.nombre = nombre;
       this.domicilio = domicilio;
       this.telefono = telefono;
       this.correo = correo;
       this.prestamoses = prestamoses;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDomicilio() {
        return this.domicilio;
    }
    
    public void setDomicilio(String domicilio) {
        this.domicilio = domicilio;
    }
    public int getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(int telefono) {
        this.telefono = telefono;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public Set<Prestamos> getPrestamoses() {
        return this.prestamoses;
    }
    
    public void setPrestamoses(Set<Prestamos> prestamoses) {
        this.prestamoses = prestamoses;
    }




}


